/**
 * Generated Outputs Panel
 *
 * Shows the deliverable documents generated by the pipeline.
 * Data source: generated_outputs table
 *
 * Renders: case_summary, grievance_email, escalation_note, evidence_checklist
 * (evidence_pack_preview has its own panel)
 */

"use client";

import { useState } from "react";
import type { GeneratedOutputRow } from "@/lib/supabase/types";

const OUTPUT_CONFIG: Record<string, { label: string; icon: string }> = {
  case_summary: { label: "Case Summary", icon: "CS" },
  grievance_email: { label: "Grievance Email", icon: "GE" },
  escalation_note: { label: "Escalation Note", icon: "EN" },
  evidence_checklist: { label: "Evidence Checklist", icon: "EC" },
};

export function GeneratedOutputsPanel({ outputs }: { outputs: GeneratedOutputRow[] }) {
  const displayOutputs = outputs.filter((output) => output.output_type !== "evidence_pack_preview");

  const [activeTab, setActiveTab] = useState<string>(displayOutputs[0]?.output_type ?? "");

  if (displayOutputs.length === 0) {
    return (
      <PanelShell title="Generated Outputs">
        <p className="text-sm font-sans text-on-surface-muted italic">Outputs will appear after pipeline completion.</p>
      </PanelShell>
    );
  }

  const activeOutput = displayOutputs.find((output) => output.output_type === activeTab);

  return (
    <PanelShell title="Generated Outputs">
      <div className="mb-6 flex flex-wrap gap-2">
        {displayOutputs.map((output) => {
          const config = OUTPUT_CONFIG[output.output_type] ?? {
            label: output.output_type,
            icon: "DOC",
          };
          return (
            <button
              key={output.output_type}
              onClick={() => setActiveTab(output.output_type)}
              className={`rounded-sm px-4 py-2 text-[10px] font-sans font-bold uppercase tracking-widest transition-colors border ${
                activeTab === output.output_type
                  ? "bg-surface text-primary border-[var(--color-border-solid)]"
                  : "bg-base text-on-surface-muted border-[var(--color-border-ghost)] hover:border-[var(--color-border-solid)]"
              }`}
            >
              {config.icon} {config.label}
            </button>
          );
        })}
      </div>

      {activeOutput && (
        <div className="rounded-sm border border-[var(--color-border-ghost)] bg-base p-6 shadow-inner">
          <div className="max-w-none">
            <div className="whitespace-pre-wrap font-serif text-sm leading-loose text-on-surface-muted">
              {renderFormattedText(activeOutput.content)}
            </div>
          </div>
        </div>
      )}
    </PanelShell>
  );
}

function renderFormattedText(content: string) {
  const lines = content.split("\n");

  return lines.map((line, lineIndex) => {
    const segments = line.split(/(\*\*.*?\*\*)/g);

    return (
      <div key={`line-${lineIndex}`}>
        {segments.map((segment, segmentIndex) => {
          const boldMatch = segment.match(/^\*\*(.*?)\*\*$/);
          if (boldMatch) {
            return (
              <strong
                key={`segment-${lineIndex}-${segmentIndex}`}
                className="font-bold text-on-base font-sans"
              >
                {boldMatch[1]}
              </strong>
            );
          }

          return (
            <span key={`segment-${lineIndex}-${segmentIndex}`}>
              {segment}
            </span>
          );
        })}
      </div>
    );
  });
}

function PanelShell({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-sm border border-[var(--color-border-solid)] bg-surface-low p-6 sm:p-8 shadow-sm">
      <h2 className="mb-6 border-b border-[var(--color-border-ghost)] pb-4 text-xs font-serif font-bold uppercase tracking-widest text-primary">
        {title}
      </h2>
      {children}
    </div>
  );
}
