/**
 * Generated Outputs Panel
 *
 * Shows the deliverable documents generated by the pipeline.
 * Data source: generated_outputs table
 *
 * Renders: case_summary, grievance_email, escalation_note, evidence_checklist
 * (evidence_pack_preview has its own panel)
 */

"use client";

import { useState } from "react";
import type { GeneratedOutputRow } from "@/lib/supabase/types";

const OUTPUT_CONFIG: Record<string, { label: string; icon: string }> = {
  case_summary: { label: "Case Summary", icon: "CS" },
  grievance_email: { label: "Grievance Email", icon: "GE" },
  escalation_note: { label: "Escalation Note", icon: "EN" },
  evidence_checklist: { label: "Evidence Checklist", icon: "EC" },
};

export function GeneratedOutputsPanel({ outputs }: { outputs: GeneratedOutputRow[] }) {
  const displayOutputs = outputs.filter((output) => output.output_type !== "evidence_pack_preview");

  const [activeTab, setActiveTab] = useState<string>(displayOutputs[0]?.output_type ?? "");

  if (displayOutputs.length === 0) {
    return (
      <PanelShell title="Generated Outputs">
        <p className="text-sm text-neutral-600">Outputs will appear after pipeline completion.</p>
      </PanelShell>
    );
  }

  const activeOutput = displayOutputs.find((output) => output.output_type === activeTab);

  return (
    <PanelShell title="Generated Outputs">
      <div className="mb-4 flex flex-wrap gap-1.5">
        {displayOutputs.map((output) => {
          const config = OUTPUT_CONFIG[output.output_type] ?? {
            label: output.output_type,
            icon: "DOC",
          };
          return (
            <button
              key={output.output_type}
              onClick={() => setActiveTab(output.output_type)}
              className={`rounded-lg px-3 py-1.5 text-xs font-medium transition-colors ${
                activeTab === output.output_type
                  ? "bg-primary-600/20 text-primary-300"
                  : "bg-neutral-800/50 text-neutral-400 hover:text-neutral-300"
              }`}
            >
              {config.icon} {config.label}
            </button>
          );
        })}
      </div>

      {activeOutput && (
        <div className="rounded-lg border border-neutral-800/50 bg-neutral-950/50 p-4">
          <div className="max-w-none">
            <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-neutral-200">
              {activeOutput.content}
            </pre>
          </div>
        </div>
      )}
    </PanelShell>
  );
}

function PanelShell({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-xl border border-neutral-800 bg-neutral-900/50 p-5">
      <h2 className="mb-4 text-xs font-semibold uppercase tracking-wider text-neutral-400">
        {title}
      </h2>
      {children}
    </div>
  );
}
